### ISSUE TITLE
Compiling Error on Linux - elix_intdef.h: No such file or directory

### ISSUE THREAD

**Issue by MajorLunaC** [lukesalisbury/luxengine#1]
When trying to compile on Linux Slackware 14.1 64-bit, I get an error indicating that a file is missing:

http://pastebin.com/1TAqdhzb

If it's the Engine Support Library: https://github.com/lukesalisbury/elix

then the problems are that elix has no make file or any other way to build it, and I see no mention of it in the dependencies for this engine, and I see no options to disable it if it's not necessary.

**Comment by lukesalisbury** [comment]
Sorry for taking so long to reply.

If building luxengine from source, you should check out elix to the same parent directory as luxengine.
For example:
/source/elix
/source/luxengine
